export const TOAST_KEY = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  SAVE_SUCCESS: 'SAVE_SUCCESS',
  CHANGE_PROFILE_SUCCESS: 'CHANGE_PROFILE_SUCCESS',
  SET_TIME_FAILED: 'SET_TIME_FAILED',
}
